### ISSUE TITLE
Week12 Lab 코드 질문

### ISSUE THREAD

**Issue by jhshynn0318** [hcid-courses/datajournalism-2019#7]
### 실행 환경

- ex) Windows10 + 64bit + 256GB / Python **3.6.5** / cmd

### 코드
오늘 수업 시간에 실습으로 진행한 Week 12 Lab 코드입니다.
수업 시간에는 jupyter notebook으로 그냥 보기만 하다가 터미널에서 실행시켜보니 말씀해주신 json error 가 나서요 ㅠㅠ
![image](https://user-images.githubusercontent.com/55327594/69520363-d0788f00-0f9f-11ea-906b-7f61c96a556a.png)

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*  

```python
# put your code segment here..

C:\Users\Samsung\Lab\Week12-Lab\robot_journalism_lab>rj_app.py
Traceback (most recent call last):
  File "C:\Users\Samsung\Lab\Week12-Lab\robot_journalism_lab\rj_app.py", line 10, in <module>
    fine_dust_data = crawler.fine_dust_fetch("관악구")
  File "C:\Users\Samsung\Lab\Week12-Lab\robot_journalism_lab\crawler.py", line 33, in fine_dust_fetch
    self.fine_dust_data = json.loads(response.read().decode("utf-8"))
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Samsung\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

# ex)
from datetime import datetime, date, time
datetime.now().strftime('%Y년 %-d월 %-m일')
```

### 설명

*작성한 코드의 목적과 내용을 최대한 자세하게 논리적으로 설명해주세요.*

### 에러 메시지

*에러 메시지를 복붙해주세요. 필요하면 특별히 에러가 나는 상황도 설명해주세요.*

```
# copy & paste your error message here..

 raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Try and Except 구문을 어디서 어떻게 넣어야하는지 알고 싶습니다 ㅠㅠ


# ex)
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-1-efd39827dcf5> in <module>()
      1 from datetime import datetime, date, time
      2 
----> 3 datetime.now().strftime('%Y년 %-d월 %-m일')

UnicodeEncodeError: 'locale' codec can't encode character '\ub144' in position 2: Illegal byte sequence
```

**Comment by eqo295** [comment]
윈도우에서 발생하는 문자 변환 문제입니다. 아래 조교가 작성한 포스팅을 참고해 주세요.

https://hcid-courses.github.io/TA/QnA/issues_with_windows_korean_strftime.html

**Comment by jhshynn0318** [comment]
> 윈도우에서 발생하는 문자 변환 문제입니다. 아래 조교가 작성한 포스팅을 참고해 주세요.
> https://hcid-courses.github.io/TA/QnA/issues_with_windows_korean_strftime.html

제가 예시 오류를 안 지워서 잘못 보신것 같은데 위의 json decode error입니다! ㅠㅠㅠ

**Comment by eqo295** [comment]
위 문제의 경우 "데이터를 특정 프레임(형식)"에 넣는 부분에서 에러가 났기 때문에 Try, Except 구문이 데이터를 하나씩 로드하는 부분에 위치해야 합니다(수업 시간에 이 문제를 두 번 설명한 바 있습니다). 다만, try~except를 하더라도 문제있는 부분을 제외하는 것에 불과하기 때문에 print등을 이용해서 어떤 형식적 문제가 발생했는지 확인해 주시길 바랍니다. 그리고 그 전에, 1) app key를 제대로 넣었는지 2) 쿼리(검색어)를 제대로 사용했는지 한번 더 확인하는 것이 좋습니다.
